def main(args):
  raise Exception('Mocked error')
